stages:
- test

jobs:
- name: Dind
  stage: test
  image: docker
  services:
  - docker:dind
  before_script:
  - apk add docker-compose
  script:
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose exec -T app composer install
  - docker-compose exec -T app php artisan key:generate
  - docker-compose exec -T app ./vendor/bin/phpunit